# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{html_mockup}
  s.version = "0.3.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Flurin Egger}]
  s.date = %q{2011-09-12}
  s.email = %q{flurin@digitpaint.nl}
  s.executables = [%q{mockup}]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "bin/mockup",
    "examples/config.ru",
    "examples/html/green.gif",
    "examples/html/index.html",
    "examples/partials/test.part.rhtml",
    "examples/script/server",
    "lib/html_mockup/cli.rb",
    "lib/html_mockup/rack/html_mockup.rb",
    "lib/html_mockup/rack/html_validator.rb",
    "lib/html_mockup/server.rb",
    "lib/html_mockup/template.rb",
    "lib/html_mockup/w3c_validator.rb"
  ]
  s.homepage = %q{http://github.com/flurin/html_mockup}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{HTML Mockup is a set of tools to create self-containing HTML mockups.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.12.0"])
      s.add_runtime_dependency(%q<rack>, [">= 1.0.0"])
    else
      s.add_dependency(%q<thor>, ["~> 0.12.0"])
      s.add_dependency(%q<rack>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.12.0"])
    s.add_dependency(%q<rack>, [">= 1.0.0"])
  end
end

